export let themes = {
    dark: {
        primaryBackground: '#121212',
        secondaryBackground: '#1F1F1F',
        headerBackground: '#161616',
        primaryTextColor: '#FFFFFF',
        secondaryTextColor: 'rgba(255, 255, 255, 0.5)',
        boardHeaders: '#FFFFFF',
        btnBg: '#BEDBB0',
        btnTextColor: '#121212',
        selectHeader: 'rgba(255, 255, 255, 0.8)',
        selectOption: 'rgba(255, 255, 255, 0.5)',
        selectListBg: '#151515',
        selectListBorder: '#BEDBB0',
        modalBackground: '#151515',
        btnModalIconPlus: '#FFFFFF',
        btnModalBg: "#161616",
        btnModalTextColor: "#161616",
        cardBg: "#121212",
        boardAddColumnBtn: "#FFFFFF",
        boardAddColumnPlus: "#121212"
    },
    light: {
        primaryBackground: '#FFFFFF',
        secondaryBackground: '#F6F6F7',
        headerBackground: '#FCFCFC',
        primaryTextColor: '#161616',
        secondaryTextColor: 'rgba(22, 22, 22, 0.5)',
        boardHeaders: '#161616B2',
        btnBg: '#BEDBB0',
        btnTextColor: '#161616',
        selectHeader: 'rgba(160, 160, 160, 0.8)',
        selectOption: '#161616',
        selectListBg: '#FCFCFC',
        selectListBorder: '#BEDBB0',
        modalBackground: '#FCFCFC',
        btnModalIconPlus: '#FFFFFF',
        btnModalBg: "#161616",
        cardBg: "#FFFFFF",
        boardAddColumnBtn: "#121212",
        boardAddColumnPlus: "#FFFFFF"
    },
    violet: {
        primaryBackground: '#5255BC',
        secondaryBackground: '#ECEDFD',
        headerBackground: '#FFFFFF',
        primaryTextColor: '#161616',
        secondaryTextColor: 'rgba(22, 22, 22, 0.5)',
        boardHeaders: '#161616',
        btnBg: '#5255BC',
        btnTextColor: '#FFFFFF',
        selectHeader: 'rgba(160, 160, 160, 0.8)',
        selectOption: '#161616',
        selectListBg: '#FCFCFC',
        selectListBorder: '#ECEDFD',
        modalBackground: '#FCFCFC',
        btnModalIconPlus: '#161616',
        btnModalBg: "#FFFFFF",
        cardBg: "#FFFFFF",
        boardAddColumnBtn: "#5255BC",
        boardAddColumnPlus: "#FFFFFF"
    }
}